In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', 500)

In [3]:
train = pd.read_csv('train.csv') # option: nrows=10000

In [4]:
test = pd.read_csv('test.csv') # option: nrows=10000

In [5]:
test_key = test['txkey']

In [6]:
train['txkey'].value_counts()

2047       1
462260     1
517545     1
523690     1
521643     1
511404     1
509357     1
515502     1
513455     1
470448     1
468401     1
460213     1
458122     1
466358     1
464311     1
486840     1
484793     1
490938     1
488891     1
478652     1
482750     1
480703     1
519592     1
497063     1
499110     1
492965     1
449934     1
404880     1
402833     1
408978     1
          ..
1762806    1
1764855    1
1742328    1
1744377    1
1738234    1
1740283    1
1734116    1
1721826    1
1801669    1
1727969    1
1795526    1
1797575    1
1775048    1
1777097    1
1770954    1
1773003    1
1783244    1
1785293    1
1779150    1
1781199    1
1834453    1
1807832    1
1809881    1
1803738    1
1805787    1
1816028    1
1811934    1
1813983    1
1725920    1
0          1
Name: txkey, Length: 1521787, dtype: int64

In [7]:
train['conam'] = train['conam'].astype(float)
train['iterm'] = train['iterm'].astype(float)

In [8]:
train['acqic'] = train['acqic'].astype(str)
train['bacno'] = train['bacno'].astype(str)
train['cano'] = train['cano'].astype(str)
train['contp'] = train['contp'].astype(str)
train['csmcu'] = train['csmcu'].astype(str)
train['ecfg'] = train['ecfg'].astype(str)
train['insfg'] = train['insfg'].astype(str)
train['etymd'] = train['etymd'].astype(str)
train['flbmk'] = train['flbmk'].astype(str)
train['flg_3dsmk'] = train['flg_3dsmk'].astype(str)
train['hcefg'] = train['hcefg'].astype(str)
train['mcc'] = train['mcc'].astype(str)
train['mchno'] = train['mchno'].astype(str)
train['ovrlt'] = train['ovrlt'].astype(str)
train['scity'] = train['scity'].astype(str)
train['stocn'] = train['stocn'].astype(str)
train['stscd'] = train['stscd'].astype(str)

In [9]:
test['conam'] = test['conam'].astype(float)
test['iterm'] = test['iterm'].astype(float)

In [10]:
test['acqic'] = test['acqic'].astype(str)
test['bacno'] = test['bacno'].astype(str)
test['cano'] = test['cano'].astype(str)
test['contp'] = test['contp'].astype(str)
test['csmcu'] = test['csmcu'].astype(str)
test['ecfg'] = test['ecfg'].astype(str)
test['insfg'] = test['insfg'].astype(str)
test['etymd'] = test['etymd'].astype(str)
test['flbmk'] = test['flbmk'].astype(str)
test['flg_3dsmk'] = test['flg_3dsmk'].astype(str)
test['hcefg'] = test['hcefg'].astype(str)
test['mcc'] = test['mcc'].astype(str)
test['mchno'] = test['mchno'].astype(str)
test['ovrlt'] = test['ovrlt'].astype(str)
test['scity'] = test['scity'].astype(str)
test['stocn'] = test['stocn'].astype(str)
test['stscd'] = test['stscd'].astype(str)

# missing values

In [11]:
train.loc[train['flbmk'] =='nan','flbmk'] = 'N'

In [12]:
train.loc[train['flg_3dsmk'] =='nan','flg_3dsmk'] = 'N'

In [13]:
test['flbmk'].fillna('N', inplace=True)
test['flg_3dsmk'].fillna('N', inplace=True)

# 該卡在三個月的交易次數 transaction_count

In [42]:
train_with_cano_only = train[['cano']]

In [43]:
cano_group = train_with_cano_only.groupby('cano')

In [44]:
transaction_count_dict = {}
ith_cano_group = 0
for i in cano_group.groups.keys():
    ith_cano_group += 1
    s = cano_group.get_group(i)
    trans =  len(s)
    
    transaction_count_dict.update( { "{}".format(i) : trans } )
    
    if(ith_cano_group%1000==0):
        print(ith_cano_group)

1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
21000
22000
23000
24000
25000
26000
27000
28000
29000
30000
31000
32000
33000
34000
35000
36000
37000
38000
39000
40000
41000
42000
43000
44000
45000
46000
47000
48000
49000
50000
51000
52000
53000
54000
55000
56000
57000
58000
59000
60000
61000
62000
63000
64000
65000
66000
67000
68000
69000
70000
71000
72000
73000
74000
75000
76000
77000
78000
79000
80000
81000
82000
83000
84000
85000
86000
87000
88000
89000
90000
91000
92000
93000
94000
95000
96000
97000
98000
99000
100000
101000
102000
103000
104000
105000
106000
107000
108000
109000
110000
111000
112000
113000
114000
115000
116000
117000
118000
119000
120000
121000
122000
123000
124000
125000
126000
127000
128000
129000

In [45]:
train['transaction_count'] = 0
for index, row in train.iterrows():
    train.at[index, 'transaction_count'] = transaction_count_dict.get(row['cano']) # checked logic
    if(index%10000 == 0):
        print(index)

0
10000
20000
30000
40000
50000
60000
70000
80000
90000
100000
110000
120000
130000
140000
150000
160000
170000
180000
190000
200000
210000
220000
230000
240000
250000
260000
270000
280000
290000
300000
310000
320000
330000
340000
350000
360000
370000
380000
390000
400000
410000
420000
430000
440000
450000
460000
470000
480000
490000
500000
510000
520000
530000
540000
550000
560000
570000
580000
590000
600000
610000
620000
630000
640000
650000
660000
670000
680000
690000
700000
710000
720000
730000
740000
750000
760000
770000
780000
790000
800000
810000
820000
830000
840000
850000
860000
870000
880000
890000
900000
910000
920000
930000
940000
950000
960000
970000
980000
990000
1000000
1010000
1020000
1030000
1040000
1050000
1060000
1070000
1080000
1090000
1100000
1110000
1120000
1130000
1140000
1150000
1160000
1170000
1180000
1190000
1200000
1210000
1220000
1230000
1240000
1250000
1260000
1270000
1280000
1290000
1300000
1310000
1320000
1330000
1340000
1350000
1360000
1370000
1380000
1390000
1400000
1410000
1420000
1430000
1440000
1450000
1460000
1470000
1480000
1490000
1500000
1510000
1520000

In [46]:
train

,acqic,bacno,cano,conam,contp,csmcu,ecfg,etymd,flbmk,flg_3dsmk,fraud_ind,hcefg,insfg,iterm,locdt,loctm,mcc,mchno,ovrlt,scity,stocn,stscd,txkey,transaction_count
0,6881,113261,38038,513.80,5,0,N,0,N,N,0,5,N,0.0,33,172652.0,457,59333,N,0,102,0,516056,80
1,0,134508,45725,465.62,5,0,N,2,N,N,0,0,N,0.0,9,105114.0,451,0,N,5817,102,0,4376,23
2,6881,15408,188328,513.80,5,0,N,0,N,N,0,5,N,0.0,6,152458.0,457,59333,N,0,102,0,483434,18
3,6716,157159,29967,1016.11,5,62,N,5,N,N,0,5,N,0.0,5,172946.0,247,50436,N,3281,102,0,1407164,57
4,5975,105985,81305,713.66,5,62,N,4,N,N,0,5,N,0.0,6,182129.0,263,93775,N,5817,102,0,1051004,63
5,0,78377,2295,465.62,5,0,N,2,N,N,0,0,N,0.0,6,104918.0,451,0,N,5817,102,0,2943,28
6,6411,94435,49219,1806.49,3,62,N,4,N,N,0,5,N,0.0,6,172624.0,339,0,N,5865,102,0,1622153,3
7,6769,112032,177989,526.88,6,62,N,2,N,N,0,5,N,0.0,7,34933.0,373,79200,N,5817,102,0,57795,84
8,6092,92294,85535,201.39,2,62,N,2,N,N,0,5,N,0.0,6,64652.0,264,8335,N,3585,102,0,836165,6
9,0,16279,110755,465.62,5,0,N,2,N,N,0,0,N,0.0,10,104447.0,451,0,N,5817,102,0,4507,4
10,6882,49387,57083,0.00,5,0,N,0,N,N,0,0,N,0.0,5,210254.0,459,2467,N,0,102,0,611092,31
11,0,24677,4485,465.62,5,0,N,2,N,N,0,0,N,0.0,9,104728.0,451,0,N,5817,102,0,4143,33
12,6883,40691,47685,513.80,5,0,N,0,N,N,0,5,N,0.0,5,172346.0,457,10045,N,0,102,0,482472,32
13,6881,12981,178029,513.80,5,0,N,0,N,N,0,5,N,0.0,6,191233.0,457,86584,N,0,102,0,483717,34
14,6882,43457,161279,0.00,5,0,N,0,N,N,0,0,N,0.0,6,164857.0,459,2459,N,0,102,0,611116,40
15,0,151054,197751,465.62,5,0,N,2,N,N,0,0,N,0.0,7,104917.0,451,0,N,5817,102,0,3387,23
16,6716,150887,4541,930.31,5,62,N,4,N,N,0,5,N,0.0,8,142028.0,329,37560,N,5820,102,0,1765957,10
17,5575,159032,42064,0.00,5,62,Y,8,N,N,0,5,N,0.0,8,114348.0,203,33794,N,2138,44,0,652944,24
18,6881,8200,5398,513.80,5,0,N,0,N,N,0,5,N,0.0,7,225727.0,457,59333,N,0,102,0,484986,10
19,6881,152257,65948,513.80,5,0,N,0,N,N,0,5,N,0.0,8,153959.0,457,68930,N,0,102,0,485608,102
20,6882,110356,133430,0.00,5,0,N,0,N,N,0,0,N,0.0,9,143657.0,459,2461,N,0,102,0,611269,15
21,0,86863,149723,465.62,5,0,N,2,N,N,0,0,N,0.0,10,105021.0,451,0,N,5817,102,0,4822,3
22,6881,68339,115453,513.80,5,0,N,0,N,N,0,5,N,0.0,10,192156.0,457,59369,N,0,102,0,488570,5
23,6881,161031,145047,683.25,5,0,N,0,N,N,0,5,N,0.0,9,121947.0,457,86584,N,0,102,0,486692,35
24,6881,147812,209978,513.80,5,0,N,0,N,N,0,5,N,0.0,11,150613.0,457,59333,N,0,102,0,489341,62
25,6769,29914,210026,298.10,5,62,N,5,N,N,0,5,N,0.0,13,195207.0,291,78438,N,3588,102,0,249362,78
26,6881,76903,83784,513.80,5,0,N,0,N,N,0,5,N,0.0,7,175543.0,457,74617,N,0,102,0,484666,10
27,2724,106875,141524,513.80,5,0,N,0,N,N,0,5,N,0.0,13,91927.0,453,544,N,0,102,0,619279,5
28,5630,157524,208050,747.35,5,74,N,4,N,N,0,5,N,0.0,14,21157.0,277,35812,N,5356,14,0,662417,78
29,0,62465,25295,465.62,5,0,N,2,N,N,0,0,N,0.0,22,104853.0,451,0,N,5817,102,0,10259,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1521757,6769,96043,74683,830.30,2,75,N,4,N,N,0,6,N,0.0,25,225025.0,264,78933,N,3588,102,0,58987,19
1521758,6769,40744,37277,1.38,5,75,Y,8,N,N,0,6,N,0.0,5,100451.0,373,79246,N,5817,102,0,420076,3
1521759,3226,53621,136755,624.72,5,75,Y,8,N,N,0,6,N,0.0,1,202101.0,250,90222,N,1170,102,0,642896,25
1521760,6769,139959,148380,1.38,5,75,Y,8,N,N,0,6,N,0.0,11,231652.0,373,79246,N,5817,102,0,421748,6
1521761,6839,73375,145511,773.66,5,75,Y,8,N,N,0,6,Y,1.0,27,141754.0,247,82174,N,5817,102,0,137685,45
1521762,6032,23287,194962,1.38,5,75,Y,2,N,N,0,6,N,0.0,11,92344.0,373,79246,N,5817,102,0,305826,14
1521763,6716,126303,109048,744.43,5,75,N,4,N,N,0,6,N,0.0,24,142652.0,207,36465,N,5820,102,0,1062148,50
1521764,6767,85141,10882,100.83,5,75,Y,8,N,N,0,6,N,0.0,25,130453.0,250,20129,N,5817,102,0,1705334,197
1521765,6716,113389,36388,1198.52,5,75,N,4,N,N,0,6,N,0.0,26,170529.0,247,60265,N,5803,102,0,1349431,8
1521766,5580,27289,182834,1163.03,5,75,Y,8,N,N,1,6,N,0.0,14,225838.0,269,20980,N,1120,104,0,663810,7
1521767,5975,28605,193350,736.92,5,75,N,5,N,N,0,6,N,0.0,16,151513.0,263,97361,N,5817,102,0,1557125,26
1521768,6716,68904,128020,475.90,5,75,N,4,N,N,0,6,N,0.0,17,193923.0,349,61296,N,5803,102,0,1629168,38
1521769,6716,16343,25595,2262.39,5,75,N,4,N,N,0,6,Y,1.0,15,113651.0,203,35096,N,5820,102,0,1698829,79
1521770,6839,94778,50039,1.38,5,75,Y,8,N,N,0,6,N,0.0,23,238.0,373,79246,N,5817,102,0,366965,16
1521771,6769,135083,125241,619.95,5,75,Y,8,N,N,0,6,N,0.0,17,192135.0,257,99963,N,5817,102,0,192742,78
1521772,6618,72653,161412,669.56,5,75,Y,2,N,N,0,6,N,0.0,16,190721.0,192,65472,N,6593,75,0,1849623,135
1521773,6769,55288,208373,1.38,5,75,Y,8,N,N,0,6,N,0.0,19,44158.0,373,79246,N,5817,102,0,365999,16
1521774,5588,95249,112041,1.38,5,75,Y,8,N,N,0,6,N,0.0,17,194234.0,296,73998,N,3426,42,0,668463,17
1521775,6716,128476,26601,1692.74,5,75,N,4,N,N,0,6,N,0.0,27,141800.0,388,49674,N,5859,102,0,1564045,20
1521776,5975,109495,38017,683.25,5,75,N,9,N,N,0,6,N,0.0,7,123351.0,263,94697,N,5817,102,0,1123162,2
1521777,6215,85771,169553,609.21,5,75,Y,2,N,N,0,6,N,0.0,14,133907.0,289,54828,N,3460,46,0,1846986,90
1521778,6769,137372,184673,1.38,5,75,Y,8,N,N,0,6,N,0.0,11,102632.0,373,79246,N,5817,102,0,133645,4
1521779,6032,2510,54094,1.38,5,75,Y,2,N,N,0,6,N,0.0,30,231435.0,248,78297,N,5817,102,0,196080,16
1521780,1801,12832,137381,1138.04,5,75,Y,8,N,N,0,6,N,0.0,1,100009.0,201,198,N,1852,98,0,642025,1
1521781,6231,139728,168027,574.36,5,75,N,5,N,N,0,6,N,0.0,28,155437.0,245,18405,N,5817,102,0,992751,51
1521782,6322,91008,15189,578.38,5,75,Y,8,N,N,0,6,N,0.0,4,191642.0,209,38222,N,5817,102,0,1478280,11
1521783,3226,145107,116252,435.32,5,75,Y,8,N,N,0,6,N,0.0,13,102338.0,192,90135,N,1458,102,0,661087,56
1521784,6769,162168,93598,1.38,5,75,Y,8,N,N,0,6,N,0.0,29,234618.0,373,79246,N,5817,102,0,167073,14
1521785,6032,45406,197460,1.38,5,75,Y,2,N,N,0,6,N,0.0,24,215218.0,373,79246,N,5817,102,0,338215,27
1521786,6716,48723,176440,406.59,5,75,N,5,N,N,0,6,N,0.0,13,163603.0,251,69607,N,2310,102,0,1055258,14

In [47]:
# combination with train and test to make the overall test to include train counts
train_test_concat = pd.concat([train, test], ignore_index=True)

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

In [48]:
# train[train['cano']=='77226'] to make sure tranaction count is right

In [49]:
#test[test['cano']=='77226'] to make sure tranaction count is right

In [50]:
test_with_cano = train_test_concat[['cano']]
cano_group = test_with_cano.groupby('cano')

transaction_count_dict = {}
ith_cano_group = 0
for i in cano_group.groups.keys():
    ith_cano_group += 1
    s = cano_group.get_group(i)
    trans =  len(s)
    
    transaction_count_dict.update( { "{}".format(i) : trans } )
    
    if(ith_cano_group%1000==0):
        print(ith_cano_group)

1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
21000
22000
23000
24000
25000
26000
27000
28000
29000
30000
31000
32000
33000
34000
35000
36000
37000
38000
39000
40000
41000
42000
43000
44000
45000
46000
47000
48000
49000
50000
51000
52000
53000
54000
55000
56000
57000
58000
59000
60000
61000
62000
63000
64000
65000
66000
67000
68000
69000
70000
71000
72000
73000
74000
75000
76000
77000
78000
79000
80000
81000
82000
83000
84000
85000
86000
87000
88000
89000
90000
91000
92000
93000
94000
95000
96000
97000
98000
99000
100000
101000
102000
103000
104000
105000
106000
107000
108000
109000
110000
111000
112000
113000
114000
115000
116000
117000
118000
119000
120000
121000
122000
123000
124000
125000
126000
127000
128000
129000
130000
131000
132000
133000
134000
135000
136000
137000
138000
139000
140000
141000
142000
143000
144000
145000
146000
147000
148000
149000
150000
151000
152000
153000
154000
155000
156000
157000
158000
159000
160000
161000
162000
163000
164000
165000
166000
167000
168000
169000
170000
171000
172000
173000
174000
175000
176000
177000
178000
179000
180000
181000
182000
183000
184000
185000
186000
187000
188000
189000
190000
191000
192000
193000
194000
195000
196000
197000
198000
199000
200000
201000
202000
203000
204000
205000
206000
207000
208000
209000
210000
211000
212000

In [51]:
test['transaction_count'] = 0
for index, row in test.iterrows():
    test.at[index, 'transaction_count'] = transaction_count_dict.get(row['cano']) # checked logic
    if(index%10000 == 0):
        print(index)

0
10000
20000
30000
40000
50000
60000
70000
80000
90000
100000
110000
120000
130000
140000
150000
160000
170000
180000
190000
200000
210000
220000
230000
240000
250000
260000
270000
280000
290000
300000
310000
320000
330000
340000
350000
360000
370000
380000
390000
400000
410000
420000

In [52]:
test

,acqic,bacno,cano,conam,contp,csmcu,ecfg,etymd,flbmk,flg_3dsmk,hcefg,insfg,iterm,locdt,loctm,mcc,mchno,ovrlt,scity,stocn,stscd,txkey,transaction_count
0,6881,163188,116799,513.80,5,0,N,0,N,N,5,N,0.0,102,215328.0,457,59360,N,0,102,0,592489,11
1,6881,163188,116799,513.80,5,0,N,0,N,N,5,N,0.0,102,222007.0,457,59360,N,0,102,0,592452,11
2,6881,163188,116799,513.80,5,0,N,0,N,N,5,N,0.0,100,170013.0,457,59360,N,0,102,0,590212,11
3,6881,163188,116799,513.80,5,0,N,0,N,N,5,N,0.0,100,165914.0,457,59360,N,0,102,0,590209,11
4,6881,163188,116799,513.80,5,0,N,0,N,N,5,N,0.0,102,215311.0,457,59360,N,0,102,0,592488,11
5,6881,163188,116799,513.80,5,0,N,0,N,N,5,N,0.0,102,222541.0,457,59360,N,0,102,2,592460,11
6,6881,163188,116799,513.80,5,0,N,0,N,N,5,N,0.0,100,162903.0,457,59360,N,0,102,0,590160,11
7,6881,163188,116799,513.80,5,0,N,0,N,N,5,N,0.0,102,222022.0,457,59360,N,0,102,0,592453,11
8,6881,163188,116799,513.80,5,0,N,0,N,N,5,N,0.0,95,182629.0,457,59360,N,0,102,0,585745,11
9,6881,163188,116799,513.80,5,0,N,0,N,N,5,N,0.0,102,221853.0,457,59360,N,0,102,0,592451,11
10,6881,163188,116799,513.80,5,0,N,0,N,N,5,N,0.0,102,222210.0,457,59360,N,0,102,2,592456,11
11,6856,70364,157281,283.82,4,62,Y,8,N,N,5,N,0.0,94,84424.0,320,69215,N,0,104,0,1176112,3
12,6716,70364,157282,676.79,5,62,N,5,N,N,5,N,0.0,115,5350.0,251,46289,N,4526,102,0,900425,9
13,6834,70364,157282,1050.50,5,62,N,4,N,N,5,N,0.0,108,24723.0,364,89867,N,5817,102,0,1611461,9
14,6839,70364,157282,380.94,5,62,N,4,N,N,5,N,0.0,112,153820.0,291,78559,N,5817,102,0,215591,9
15,6716,70364,157280,874.16,5,62,Y,2,N,N,5,N,0.0,103,20507.0,248,38849,N,5820,102,0,1751664,3
16,6839,70364,157282,380.94,5,62,N,4,N,N,5,N,0.0,107,163042.0,291,78559,N,5817,102,0,185563,9
17,6881,70364,157282,513.80,5,0,N,0,N,N,5,N,0.0,119,185010.0,457,59333,N,0,102,0,608423,9
18,6716,70364,157280,917.33,5,62,Y,2,N,N,5,N,0.0,111,40611.0,248,38849,N,5820,102,0,1041457,3
19,6838,70364,157282,771.78,2,62,N,2,N,N,5,N,0.0,113,141455.0,264,7970,N,5817,102,0,899509,9
20,6881,70364,157282,513.80,5,0,N,0,N,N,5,N,0.0,116,140518.0,457,59333,N,0,102,0,605308,9
21,6881,70364,157282,0.00,5,0,N,0,N,N,0,N,0.0,113,213324.0,458,0,N,0,102,0,602666,9
22,6839,70364,157281,380.94,5,62,N,4,N,N,5,N,0.0,91,150047.0,291,78559,N,5817,102,0,268390,3
23,6876,70364,157281,758.99,4,62,Y,8,N,N,5,N,0.0,94,84426.0,320,131,N,0,25,0,1390047,3
24,6716,70364,157280,812.26,5,62,Y,2,N,N,5,N,0.0,119,34456.0,248,38849,N,5820,102,0,1616943,3
25,6881,70364,157282,513.80,5,0,N,0,N,N,5,N,0.0,113,213335.0,457,59369,N,0,102,0,602665,9
26,6859,156567,21219,0.08,5,62,N,2,N,N,5,N,0.0,119,160445.0,250,48764,N,0,1,0,1831585,30
27,6716,156567,21219,253.80,5,62,N,5,N,N,5,N,0.0,114,34055.0,294,49304,N,5859,102,0,1186182,30
28,6859,156567,21219,391.59,5,62,N,2,N,N,5,N,0.0,119,161031.0,250,48764,N,0,1,0,1402780,30
29,6859,156567,21219,391.59,5,62,N,2,N,N,5,N,0.0,119,160909.0,250,48764,N,0,1,0,1045947,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421635,5962,1105,8341,999.98,5,62,Y,8,N,N,5,N,0.0,97,91728.0,317,77516,N,6031,102,0,1034535,28
421636,5962,1105,8341,776.78,5,62,Y,8,N,N,5,N,0.0,102,113517.0,317,77516,N,6031,102,0,1323068,28
421637,5962,1105,8341,999.98,5,62,Y,8,N,N,5,N,0.0,104,93436.0,317,77516,N,6031,102,0,1037920,28
421638,5962,1105,8341,776.78,5,62,Y,8,N,N,5,N,0.0,102,113400.0,317,77516,N,6031,102,0,1537063,28
421639,0,1105,8340,465.62,5,0,N,2,N,N,0,N,0.0,97,100959.0,451,0,N,5817,102,0,47480,6
421640,5962,1105,8341,776.78,5,62,Y,8,N,N,5,N,0.0,102,113827.0,317,77516,N,6031,102,0,1608577,28
421641,5962,1105,8341,999.98,5,62,Y,8,N,N,5,N,0.0,104,93535.0,317,77516,N,6031,102,0,1037924,28
421642,6716,160471,43043,1028.77,4,62,N,2,N,N,5,Y,1.0,96,183149.0,247,34949,N,5817,102,0,1462822,1
421643,6752,154675,115418,716.41,4,26,Y,2,N,N,5,N,0.0,96,72503.0,318,68603,N,5932,52,0,1932478,9
421644,6752,154675,115418,873.69,4,26,Y,2,N,N,5,N,0.0,100,3151.0,318,68603,N,5932,52,0,1935813,9
421645,6752,154675,115418,244.49,4,26,Y,2,N,N,5,N,0.0,118,21542.0,318,68603,N,5932,52,0,1951795,9
421646,6677,154675,115418,588.39,5,62,N,5,N,N,5,N,0.0,100,120925.0,251,26306,N,6022,102,0,1036006,9
421647,6752,154675,115418,866.50,4,26,Y,2,N,N,5,N,0.0,103,73249.0,318,68603,N,5932,52,0,1938590,9
421648,6752,154675,115418,0.08,4,26,Y,2,N,N,5,N,0.0,120,123322.0,318,68603,N,5932,52,0,1953793,9
421649,6231,154675,115418,325.94,5,62,N,5,N,N,5,N,0.0,117,175847.0,277,18352,N,5817,102,0,1331090,9
421650,6752,154675,115418,885.30,4,26,Y,2,N,N,5,N,0.0,110,81612.0,318,68603,N,5932,52,0,1944814,9
421651,6752,154675,115418,906.60,4,26,Y,2,N,N,5,N,0.0,111,211823.0,318,68603,N,5932,52,0,1946378,9
421652,6769,64349,122777,284.95,5,62,N,5,N,N,5,N,0.0,104,101026.0,251,78060,N,5817,102,0,270871,4
421653,6769,64349,122777,473.36,5,62,N,5,N,N,5,N,0.0,107,104828.0,251,77981,N,5817,102,0,358272,4
421654,6769,64349,122777,465.09,5,62,N,5,N,N,5,N,0.0,107,105147.0,286,77983,N,5817,102,0,329145,4
421655,6769,64349,122777,495.92,5,62,N,5,N,N,5,N,0.0,100,113232.0,251,77981,N,5817,102,0,385657,4
421656,6769,106156,4897,859.57,5,62,N,5,N,N,5,N,0.0,107,142857.0,251,77989,N,5817,102,0,214574,1
421657,6231,162079,97150,1212.15,5,62,N,4,N,N,5,N,0.0,115,130950.0,257,13835,N,5817,102,0,1043700,2
421658,6231,162079,97150,1282.55,5,62,N,4,N,N,5,N,0.0,103,202818.0,247,6476,N,5817,102,0,966092,2
421659,6854,155409,107022,1100.61,4,62,Y,8,N,N,5,N,0.0,99,145525.0,319,53458,N,6031,102,0,963833,1
421660,5975,147326,79511,633.76,5,62,N,2,N,N,5,N,0.0,116,111228.0,343,87282,N,5817,102,0,1187507,1
421661,6716,14305,136493,952.84,5,62,N,5,N,N,8,N,0.0,107,85839.0,245,48784,N,5859,102,0,1182598,1
421662,5975,156543,137963,713.42,5,62,N,4,N,N,5,N,0.0,111,184921.0,263,98326,N,5817,102,0,898724,1
421663,6231,156543,137964,903.94,5,62,N,5,N,N,5,N,0.0,114,144434.0,251,17763,N,5817,102,0,971467,1
421664,6769,131985,98699,760.09,5,62,N,4,N,N,5,N,0.0,116,162804.0,251,78019,N,3294,102,0,101230,1

In [53]:
#回來看 test之transaction count有無包含train的count

每一筆交易金額減掉該卡三個月消費金額的平均 ( 標準化? 但原本資料已經過變化)

In [54]:
train_with_cano_amount = train[['cano','conam']]

In [55]:
cano_amount_group = train_with_cano_amount.groupby('cano')

In [56]:
# for i in cano_amount_group.groups.keys():
# #     ith_cano_group += 1
#     s = cano_amount_group.get_group(i)
#     amount_sum = s.sum()['conam']
#     print(amount_sum)

In [57]:
avg_amount = {}
ith_cano_group = 0
for i in cano_amount_group.groups.keys():
    ith_cano_group += 1
    s = cano_amount_group.get_group(i)
    amount_sum = s.sum()['conam'] / len(s)
    
    avg_amount.update( { "{}".format(i) : amount_sum } )
    
    if(ith_cano_group%1000==0):
        print(ith_cano_group)

1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
21000
22000
23000
24000
25000
26000
27000
28000
29000
30000
31000
32000
33000
34000
35000
36000
37000
38000
39000
40000
41000
42000
43000
44000
45000
46000
47000
48000
49000
50000
51000
52000
53000
54000
55000
56000
57000
58000
59000
60000
61000
62000
63000
64000
65000
66000
67000
68000
69000
70000
71000
72000
73000
74000
75000
76000
77000
78000
79000
80000
81000
82000
83000
84000
85000
86000
87000
88000
89000
90000
91000
92000
93000
94000
95000
96000
97000
98000
99000
100000
101000
102000
103000
104000
105000
106000
107000
108000
109000
110000
111000
112000
113000
114000
115000
116000
117000
118000
119000
120000
121000
122000
123000
124000
125000
126000
127000
128000
129000

In [58]:
train['conam_minus_avg'] = 0.5 # make sure this column is in decimal,god damnit make me debugging so long
for index, row in train.iterrows():
    avg = avg_amount.get(row['cano']) # checked logic
    train.at[index, 'conam_minus_avg'] = train['conam'][index] - avg # checked logic
    if(index%10000 == 0):
        print(index)

0
10000
20000
30000
40000
50000
60000
70000
80000
90000
100000
110000
120000
130000
140000
150000
160000
170000
180000
190000
200000
210000
220000
230000
240000
250000
260000
270000
280000
290000
300000
310000
320000
330000
340000
350000
360000
370000
380000
390000
400000
410000
420000
430000
440000
450000
460000
470000
480000
490000
500000
510000
520000
530000
540000
550000
560000
570000
580000
590000
600000
610000
620000
630000
640000
650000
660000
670000
680000
690000
700000
710000
720000
730000
740000
750000
760000
770000
780000
790000
800000
810000
820000
830000
840000
850000
860000
870000
880000
890000
900000
910000
920000
930000
940000
950000
960000
970000
980000
990000
1000000
1010000
1020000
1030000
1040000
1050000
1060000
1070000
1080000
1090000
1100000
1110000
1120000
1130000
1140000
1150000
1160000
1170000
1180000
1190000
1200000
1210000
1220000
1230000
1240000
1250000
1260000
1270000
1280000
1290000
1300000
1310000
1320000
1330000
1340000
1350000
1360000
1370000
1380000
1390000
1400000
1410000
1420000
1430000
1440000
1450000
1460000
1470000
1480000
1490000
1500000
1510000
1520000

In [59]:
test_with_cano_amount = test[['cano','conam']]
test_cano_amount_group = test_with_cano_amount.groupby('cano')

In [60]:
avg_amount = {}
ith_cano_group = 0
for i in test_cano_amount_group.groups.keys():
    ith_cano_group += 1
    s = test_cano_amount_group.get_group(i)
    amount_sum = s.sum()['conam'] / len(s)
    
    avg_amount.update( { "{}".format(i) : amount_sum } )
    
    if(ith_cano_group%10000==0):
        print(ith_cano_group)

10000
20000
30000
40000
50000
60000
70000
80000

In [61]:
test['conam_minus_avg'] = 0.5 # make sure this column is in decimal,god damnit make me debugging so long
for index, row in test.iterrows():
    avg = avg_amount.get(row['cano']) # checked logic
    test.at[index, 'conam_minus_avg'] = test['conam'][index] - avg # checked logic
    if(index%10000 == 0):
        print(index)

0
10000
20000
30000
40000
50000
60000
70000
80000
90000
100000
110000
120000
130000
140000
150000
160000
170000
180000
190000
200000
210000
220000
230000
240000
250000
260000
270000
280000
290000
300000
310000
320000
330000
340000
350000
360000
370000
380000
390000
400000
410000
420000

消費地國別變動激烈程度 (三個月) :   消費地國別次數/該卡號消費次數   
這邊做的假設是，前三個月的消費地國別已經代表此人常消費的國別

In [62]:
train_with_cano_stocn = train[['cano','stocn']]

In [63]:
cano_stocn_group = train_with_cano_stocn.groupby('cano')

stocn_count_dic = {}
ith_cano_group = 0
for i in cano_stocn_group.groups.keys():
    ith_cano_group += 1
    s = cano_stocn_group.get_group(i)
    stocn_count = s['stocn'].value_counts()
    stocn_prop_dict = {}
    for n,v in stocn_count.iteritems():
        stocn_prop_dict.update({n : v / len(s)})

    stocn_count_dic.update( { "{}".format(i) : stocn_prop_dict } )
    
    if(ith_cano_group%1000==0):
        print(ith_cano_group)

1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
21000
22000
23000
24000
25000
26000
27000
28000
29000
30000
31000
32000
33000
34000
35000
36000
37000
38000
39000
40000
41000
42000
43000
44000
45000
46000
47000
48000
49000
50000
51000
52000
53000
54000
55000
56000
57000
58000
59000
60000
61000
62000
63000
64000
65000
66000
67000
68000
69000
70000
71000
72000
73000
74000
75000
76000
77000
78000
79000
80000
81000
82000
83000
84000
85000
86000
87000
88000
89000
90000
91000
92000
93000
94000
95000
96000
97000
98000
99000
100000
101000
102000
103000
104000
105000
106000
107000
108000
109000
110000
111000
112000
113000
114000
115000
116000
117000
118000
119000
120000
121000
122000
123000
124000
125000
126000
127000
128000
129000

In [64]:
train['stocn_cano_proportion'] = 0.5 # need to be float
for index, row in train.iterrows():
    train.at[index,'stocn_cano_proportion'] = stocn_count_dic[row['cano']].get(row['stocn'])
    if(index%10000 == 0):
        print(index)

0
10000
20000
30000
40000
50000
60000
70000
80000
90000
100000
110000
120000
130000
140000
150000
160000
170000
180000
190000
200000
210000
220000
230000
240000
250000
260000
270000
280000
290000
300000
310000
320000
330000
340000
350000
360000
370000
380000
390000
400000
410000
420000
430000
440000
450000
460000
470000
480000
490000
500000
510000
520000
530000
540000
550000
560000
570000
580000
590000
600000
610000
620000
630000
640000
650000
660000
670000
680000
690000
700000
710000
720000
730000
740000
750000
760000
770000
780000
790000
800000
810000
820000
830000
840000
850000
860000
870000
880000
890000
900000
910000
920000
930000
940000
950000
960000
970000
980000
990000
1000000
1010000
1020000
1030000
1040000
1050000
1060000
1070000
1080000
1090000
1100000
1110000
1120000
1130000
1140000
1150000
1160000
1170000
1180000
1190000
1200000
1210000
1220000
1230000
1240000
1250000
1260000
1270000
1280000
1290000
1300000
1310000
1320000
1330000
1340000
1350000
1360000
1370000
1380000
1390000
1400000
1410000
1420000
1430000
1440000
1450000
1460000
1470000
1480000
1490000
1500000
1510000
1520000

In [65]:
# combination with train and test to make the overall test to include train proportions
train_test_concat = pd.concat([train, test], ignore_index=True)

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

In [66]:
#do same thing with test set again
test_with_cano_stocn = train_test_concat[['cano','stocn']]

In [67]:
cano_stocn_group  = test_with_cano_stocn.groupby('cano')


stocn_count_dic = {}

ith_cano_group = 0
for i in cano_stocn_group.groups.keys():
    ith_cano_group += 1
    s = cano_stocn_group.get_group(i)
    stocn_count = s['stocn'].value_counts()
    stocn_prop_dict = {}
    for n,v in stocn_count.iteritems():
        stocn_prop_dict.update({n : v / len(s)})

    stocn_count_dic.update( { "{}".format(i) : stocn_prop_dict } )
    
    if(ith_cano_group%1000==0):
        print(ith_cano_group)

1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
21000
22000
23000
24000
25000
26000
27000
28000
29000
30000
31000
32000
33000
34000
35000
36000
37000
38000
39000
40000
41000
42000
43000
44000
45000
46000
47000
48000
49000
50000
51000
52000
53000
54000
55000
56000
57000
58000
59000
60000
61000
62000
63000
64000
65000
66000
67000
68000
69000
70000
71000
72000
73000
74000
75000
76000
77000
78000
79000
80000
81000
82000
83000
84000
85000
86000
87000
88000
89000
90000
91000
92000
93000
94000
95000
96000
97000
98000
99000
100000
101000
102000
103000
104000
105000
106000
107000
108000
109000
110000
111000
112000
113000
114000
115000
116000
117000
118000
119000
120000
121000
122000
123000
124000
125000
126000
127000
128000
129000
130000
131000
132000
133000
134000
135000
136000
137000
138000
139000
140000
141000
142000
143000
144000
145000
146000
147000
148000
149000
150000
151000
152000
153000
154000
155000
156000
157000
158000
159000
160000
161000
162000
163000
164000
165000
166000
167000
168000
169000
170000
171000
172000
173000
174000
175000
176000
177000
178000
179000
180000
181000
182000
183000
184000
185000
186000
187000
188000
189000
190000
191000
192000
193000
194000
195000
196000
197000
198000
199000
200000
201000
202000
203000
204000
205000
206000
207000
208000
209000
210000
211000
212000

In [68]:
test['stocn_cano_proportion'] = 0.5 # need to be float
for index, row in test.iterrows():
    test.at[index,'stocn_cano_proportion'] = stocn_count_dic[row['cano']].get(row['stocn'])
    if(index%10000 == 0):
        print(index)

0
10000
20000
30000
40000
50000
60000
70000
80000
90000
100000
110000
120000
130000
140000
150000
160000
170000
180000
190000
200000
210000
220000
230000
240000
250000
260000
270000
280000
290000
300000
310000
320000
330000
340000
350000
360000
370000
380000
390000
400000
410000
420000

mcc scity proportion feature

In [69]:
train_with_cano_mcc_city = train[['cano','mcc','scity']]

In [70]:
cano_mcc_scity_group = train_with_cano_mcc_city.groupby('cano')

mcc_count_dic = {}
scity_count_dic = {}
ith_cano_group = 0

#checked logic
for i in cano_mcc_scity_group.groups.keys():
    ith_cano_group += 1
    s = cano_mcc_scity_group.get_group(i)
    mcc_count = s['mcc'].value_counts()
    scity_count = s['scity'].value_counts()
    mcc_prop_dict = {}
    scity_prop_dict = {}
    for n,v in mcc_count.iteritems():
        mcc_prop_dict.update({n : v / len(s)})
    for n,v in scity_count.iteritems():
        scity_prop_dict.update({n : v / len(s)})
        
        
    mcc_count_dic.update( { "{}".format(i) : mcc_prop_dict } )
    scity_count_dic.update( { "{}".format(i) : scity_prop_dict } )
    if(ith_cano_group%1000==0):
        print(ith_cano_group)

1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
21000
22000
23000
24000
25000
26000
27000
28000
29000
30000
31000
32000
33000
34000
35000
36000
37000
38000
39000
40000
41000
42000
43000
44000
45000
46000
47000
48000
49000
50000
51000
52000
53000
54000
55000
56000
57000
58000
59000
60000
61000
62000
63000
64000
65000
66000
67000
68000
69000
70000
71000
72000
73000
74000
75000
76000
77000
78000
79000
80000
81000
82000
83000
84000
85000
86000
87000
88000
89000
90000
91000
92000
93000
94000
95000
96000
97000
98000
99000
100000
101000
102000
103000
104000
105000
106000
107000
108000
109000
110000
111000
112000
113000
114000
115000
116000
117000
118000
119000
120000
121000
122000
123000
124000
125000
126000
127000
128000
129000

In [71]:
train['mcc_cano_proportion'] = 0.5 # need to be float
train['scity_cano_proportion'] = 0.5 # need to be float
for index, row in train.iterrows():
    train.at[index,'mcc_cano_proportion'] = mcc_count_dic[row['cano']].get(row['mcc'])
    train.at[index,'scity_cano_proportion'] = scity_count_dic[row['cano']].get(row['scity'])
    if(index%10000 == 0):
        print(index)

0
10000
20000
30000
40000
50000
60000
70000
80000
90000
100000
110000
120000
130000
140000
150000
160000
170000
180000
190000
200000
210000
220000
230000
240000
250000
260000
270000
280000
290000
300000
310000
320000
330000
340000
350000
360000
370000
380000
390000
400000
410000
420000
430000
440000
450000
460000
470000
480000
490000
500000
510000
520000
530000
540000
550000
560000
570000
580000
590000
600000
610000
620000
630000
640000
650000
660000
670000
680000
690000
700000
710000
720000
730000
740000
750000
760000
770000
780000
790000
800000
810000
820000
830000
840000
850000
860000
870000
880000
890000
900000
910000
920000
930000
940000
950000
960000
970000
980000
990000
1000000
1010000
1020000
1030000
1040000
1050000
1060000
1070000
1080000
1090000
1100000
1110000
1120000
1130000
1140000
1150000
1160000
1170000
1180000
1190000
1200000
1210000
1220000
1230000
1240000
1250000
1260000
1270000
1280000
1290000
1300000
1310000
1320000
1330000
1340000
1350000
1360000
1370000
1380000
1390000
1400000
1410000
1420000
1430000
1440000
1450000
1460000
1470000
1480000
1490000
1500000
1510000
1520000

In [72]:
# combination with train and test to make the overall test to include train proportions
train_test_concat = pd.concat([train, test], ignore_index=True)
#do same thing with test set again
test_with_cano_mcc_city = train_test_concat[['cano','mcc','scity']]

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

In [73]:
cano_mcc_scity_group = test_with_cano_mcc_city.groupby('cano')

mcc_count_dic = {}
scity_count_dic = {}
ith_cano_group = 0

#checked logic
for i in cano_mcc_scity_group.groups.keys():
    ith_cano_group += 1
    s = cano_mcc_scity_group.get_group(i)
    mcc_count = s['mcc'].value_counts()
    scity_count = s['scity'].value_counts()
    mcc_prop_dict = {}
    scity_prop_dict = {}
    for n,v in mcc_count.iteritems():
        mcc_prop_dict.update({n : v / len(s)})
    for n,v in scity_count.iteritems():
        scity_prop_dict.update({n : v / len(s)})
        
        
    mcc_count_dic.update( { "{}".format(i) : mcc_prop_dict } )
    scity_count_dic.update( { "{}".format(i) : scity_prop_dict } )
    if(ith_cano_group%1000==0):
        print(ith_cano_group)

1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
21000
22000
23000
24000
25000
26000
27000
28000
29000
30000
31000
32000
33000
34000
35000
36000
37000
38000
39000
40000
41000
42000
43000
44000
45000
46000
47000
48000
49000
50000
51000
52000
53000
54000
55000
56000
57000
58000
59000
60000
61000
62000
63000
64000
65000
66000
67000
68000
69000
70000
71000
72000
73000
74000
75000
76000
77000
78000
79000
80000
81000
82000
83000
84000
85000
86000
87000
88000
89000
90000
91000
92000
93000
94000
95000
96000
97000
98000
99000
100000
101000
102000
103000
104000
105000
106000
107000
108000
109000
110000
111000
112000
113000
114000
115000
116000
117000
118000
119000
120000
121000
122000
123000
124000
125000
126000
127000
128000
129000
130000
131000
132000
133000
134000
135000
136000
137000
138000
139000
140000
141000
142000
143000
144000
145000
146000
147000
148000
149000
150000
151000
152000
153000
154000
155000
156000
157000
158000
159000
160000
161000
162000
163000
164000
165000
166000
167000
168000
169000
170000
171000
172000
173000
174000
175000
176000
177000
178000
179000
180000
181000
182000
183000
184000
185000
186000
187000
188000
189000
190000
191000
192000
193000
194000
195000
196000
197000
198000
199000
200000
201000
202000
203000
204000
205000
206000
207000
208000
209000
210000
211000
212000

In [74]:
test['mcc_cano_proportion'] = 0.5 # need to be float
test['scity_cano_proportion'] = 0.5 # need to be float
for index, row in test.iterrows():
    test.at[index,'mcc_cano_proportion'] = mcc_count_dic[row['cano']].get(row['mcc'])
    test.at[index,'scity_cano_proportion'] = scity_count_dic[row['cano']].get(row['scity'])
    if(index%10000 == 0):
        print(index)

0
10000
20000
30000
40000
50000
60000
70000
80000
90000
100000
110000
120000
130000
140000
150000
160000
170000
180000
190000
200000
210000
220000
230000
240000
250000
260000
270000
280000
290000
300000
310000
320000
330000
340000
350000
360000
370000
380000
390000
400000
410000
420000

train[train['cano']=='138672']

train[train['cano']=='138672']['mcc'].value_counts()['289']

test[test['cano']=='138672']['mcc'].value_counts()['289']

test[test['cano']=='138672']

In [ ]:
# (23 + 9 ) / 117 = 0.2735042735   ==  mcc[289]之 mcc proportion

# 每個cano group 裡 資料內的similiarty
# similarity feature
# Unfinished

In [39]:
def jaccard_similarity(list1, list2):
    intersection = len(list(set(list1).intersection(set(list2))))
    union = (len(set(list1)) + len(set(list2))) - intersection
    return float(intersection) / union

# feature : group by cano, locdt 出現的次數 / 總交易次數

In [75]:
train_with_cano_locdt = train[['cano','locdt']]

In [76]:
cano_locdt_group = train_with_cano_locdt.groupby('cano')

In [77]:
locdt_count_dic = {}
ith_cano_group = 0
for i in cano_locdt_group.groups.keys():
    ith_cano_group += 1
    s = cano_locdt_group.get_group(i)
    locdt_count = s['locdt'].value_counts()
    locdt_prop_dict = {}
    for n,v in locdt_count.iteritems():
        locdt_prop_dict.update({n : v / len(s)})

    locdt_count_dic.update( { "{}".format(i) : locdt_prop_dict } )
    
    if(ith_cano_group%1000==0):
        print(ith_cano_group)

1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
21000
22000
23000
24000
25000
26000
27000
28000
29000
30000
31000
32000
33000
34000
35000
36000
37000
38000
39000
40000
41000
42000
43000
44000
45000
46000
47000
48000
49000
50000
51000
52000
53000
54000
55000
56000
57000
58000
59000
60000
61000
62000
63000
64000
65000
66000
67000
68000
69000
70000
71000
72000
73000
74000
75000
76000
77000
78000
79000
80000
81000
82000
83000
84000
85000
86000
87000
88000
89000
90000
91000
92000
93000
94000
95000
96000
97000
98000
99000
100000
101000
102000
103000
104000
105000
106000
107000
108000
109000
110000
111000
112000
113000
114000
115000
116000
117000
118000
119000
120000
121000
122000
123000
124000
125000
126000
127000
128000
129000

In [78]:
train['locdt_cano_proportion'] = 0.5 # need to be float
for index, row in train.iterrows():
    train.at[index,'locdt_cano_proportion'] = locdt_count_dic[row['cano']].get(row['locdt'])
    if(index%10000 == 0):
        print(index)

0
10000
20000
30000
40000
50000
60000
70000
80000
90000
100000
110000
120000
130000
140000
150000
160000
170000
180000
190000
200000
210000
220000
230000
240000
250000
260000
270000
280000
290000
300000
310000
320000
330000
340000
350000
360000
370000
380000
390000
400000
410000
420000
430000
440000
450000
460000
470000
480000
490000
500000
510000
520000
530000
540000
550000
560000
570000
580000
590000
600000
610000
620000
630000
640000
650000
660000
670000
680000
690000
700000
710000
720000
730000
740000
750000
760000
770000
780000
790000
800000
810000
820000
830000
840000
850000
860000
870000
880000
890000
900000
910000
920000
930000
940000
950000
960000
970000
980000
990000
1000000
1010000
1020000
1030000
1040000
1050000
1060000
1070000
1080000
1090000
1100000
1110000
1120000
1130000
1140000
1150000
1160000
1170000
1180000
1190000
1200000
1210000
1220000
1230000
1240000
1250000
1260000
1270000
1280000
1290000
1300000
1310000
1320000
1330000
1340000
1350000
1360000
1370000
1380000
1390000
1400000
1410000
1420000
1430000
1440000
1450000
1460000
1470000
1480000
1490000
1500000
1510000
1520000

In [79]:
# combination with train and test to make the overall test to include train proportions
train_test_concat = pd.concat([train, test], ignore_index=True)

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

In [82]:
#do same thing with test set again
test_with_cano_locdt = train_test_concat[['cano','locdt']]

In [83]:
cano_locdt_group  = test_with_cano_locdt.groupby('cano')


locdt_count_dic = {}

ith_cano_group = 0
for i in cano_locdt_group.groups.keys():
    ith_cano_group += 1
    s = cano_locdt_group.get_group(i)
    locdt_count = s['locdt'].value_counts()
    locdt_prop_dict = {}
    for n,v in locdt_count.iteritems():
        locdt_prop_dict.update({n : v / len(s)})

    locdt_count_dic.update( { "{}".format(i) : locdt_prop_dict } )
    
    if(ith_cano_group%1000==0):
        print(ith_cano_group)

1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
21000
22000
23000
24000
25000
26000
27000
28000
29000
30000
31000
32000
33000
34000
35000
36000
37000
38000
39000
40000
41000
42000
43000
44000
45000
46000
47000
48000
49000
50000
51000
52000
53000
54000
55000
56000
57000
58000
59000
60000
61000
62000
63000
64000
65000
66000
67000
68000
69000
70000
71000
72000
73000
74000
75000
76000
77000
78000
79000
80000
81000
82000
83000
84000
85000
86000
87000
88000
89000
90000
91000
92000
93000
94000
95000
96000
97000
98000
99000
100000
101000
102000
103000
104000
105000
106000
107000
108000
109000
110000
111000
112000
113000
114000
115000
116000
117000
118000
119000
120000
121000
122000
123000
124000
125000
126000
127000
128000
129000
130000
131000
132000
133000
134000
135000
136000
137000
138000
139000
140000
141000
142000
143000
144000
145000
146000
147000
148000
149000
150000
151000
152000
153000
154000
155000
156000
157000
158000
159000
160000
161000
162000
163000
164000
165000
166000
167000
168000
169000
170000
171000
172000
173000
174000
175000
176000
177000
178000
179000
180000
181000
182000
183000
184000
185000
186000
187000
188000
189000
190000
191000
192000
193000
194000
195000
196000
197000
198000
199000
200000
201000
202000
203000
204000
205000
206000
207000
208000
209000
210000
211000
212000

In [84]:
test['locdt_cano_proportion'] = 0.5 # need to be float
for index, row in test.iterrows():
    test.at[index,'locdt_cano_proportion'] = stocn_count_dic[row['cano']].get(row['locdt'])
    if(index%10000 == 0):
        print(index)

0
10000
20000
30000
40000
50000
60000
70000
80000
90000
100000
110000
120000
130000
140000
150000
160000
170000
180000
190000
200000
210000
220000
230000
240000
250000
260000
270000
280000
290000
300000
310000
320000
330000
340000
350000
360000
370000
380000
390000
400000
410000
420000

# 該人該國平均花費金額？
group by cano  
group by stocn  
conam / len(stocn.value_counts())

# 想辦法融合locdt跟loctm
然後計算此次交易與上一次交易的時間差距

In [87]:
train.to_csv('train_feature.csv',index=False)

In [88]:
test.to_csv('test_feature.csv',index=False)